general:
  root_path: ../../vnncomp2021/benchmarks/cifar10_resnet  # Please update this path to point to the VNN-COMP 2021 repo.
  csv_name: cifar10_resnet_instances.csv
data:
  dataset: CIFAR
  start: 0
  end: 72
solver:
  batch_size: 2000
  beta-crown:
    lr_beta: 0.01
attack:
  pgd_order: skip
bab:
  branching:
    reduceop: max
  cut:
    enabled: True
    cplex_cuts: True
    bab_cut: True
    lr_decay: 0.9
