general:
  root_path: ../../vnncomp2021/benchmarks/cifar2020  # Please update this path to point to the VNN-COMP 2021 repo
  csv_name: cifar2020_instances.csv
data:
  start: 82
  end: 138
solver:
  batch_size: 200
  beta-crown:
    lr_beta: 0.01
bab:
  branching:
    reduceop: max
    candidates: 10
