general:
  root_path: ../../vnncomp2021/benchmarks/eran  # Please update this path to point to the VNN-COMP 2021 repo
  csv_name: eran_instances.csv
  complete_verifier: bab-refine
model:
  onnx_optimization_flags: remove_ineffective_layers, remove_relu_in_last_layer
data:
  start: 0
  end: 36
solver:
  batch_size: 500
  beta-crown:
    iteration: 20
  mip:
    parallel_solvers: 16
    refine_neuron_time_percentage: 0.8
