# Configuration file for running the sri_resnet_a benchmark (all properties).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/metaroom
  csv_name: instances.csv
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
solver:
  batch_size: 256
  beta-crown:
    lr_beta: 0.05
    iteration: 10
  prune_after_crown: True
bab:
  initial_max_domains: 100
  branching:
    reduceop: max
    candidates: 10
  interm_transfer: False
attack:
  pgd_order: middle
