# Configuration file for running the nn4sys_2023 benchmark (pensieve models).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/nn4sys
  csv_name: instances.csv
  enable_incomplete_verification: false
  loss_reduction_func: max
  conv_mode: matrix
  no_batchdim_buffers: true
solver:
  batch_size: 256
  auto_enlarge_batch_size: true
  bound_prop_method: forward+crown
bab:
  initial_max_domains: 1000
  branching:
    method: sb
    sb_coeff_thresh: 0.1
    input_split:
      enable: True
      adv_check: .inf
attack:
  pgd_order: input_bab
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"  # Fix batch dimension in this onnx.
