# Configuration file for running the tllverifybench benchmark (all properties).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/tllverifybench
  csv_name: instances.csv
  enable_incomplete_verification: False
  conv_mode: matrix
model:
  onnx_optimization_flags: merge_linear
solver:
  batch_size: 1500  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  branching:
    method: naive
    input_split:
      enable: True
attack:
  pgd_order: before
