general:
  enable_incomplete_verification: False
model:
  name: cnn_4layer_b
  path: models/sdp/cifar_cnn_b_adv.model
data:
  dataset: CIFAR_SAMPLE
specification:
  epsilon: 0.3
  robustness_type: runnerup
attack:
  pgd_order: skip
solver:
  batch_size: 300
  beta-crown:
    iteration: 20
bab:
  timeout: 180
  decision_thresh: .inf
