model:
  name: cnn_4layer_b4
  path: models/sdp/cifar_cnn_b_adv4.model
data:
  dataset: CIFAR_SDP
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 50
solver:
  batch_size: 256
  beta-crown:
    iteration: 20
bab:
  timeout: 200 
