general:
  enable_incomplete_verification: False
model:
  name: mnist_cnn_4layer
  path: models/sdp/mnist_cnn_a_adv.model
data:
  dataset: MNIST_SAMPLE
specification:
  epsilon: 0.3
  robustness_type: runnerup
attack:
  pgd_order: skip
solver:
  batch_size: 300
  beta-crown:
    iteration: 20
bab:
  timeout: 180
  decision_thresh: .inf
  branching:
    reduceop: max
