model:
  name: mnist_cnn_4layer
  path: models/sdp/mnist_cnn_a_adv.model
data:
  dataset: MNIST_SDP
specification:
  epsilon: 0.3
attack:
  pgd_restarts: 50
solver:
  batch_size: 4096 # 1024
  beta-crown:
    iteration: 20 # 20
    lr_beta: 0.005 # 0.05
bab:
  timeout: 200 # 180
  branching:
    reduceop: max
