model:
  name: cnn_4layer_adv
  path: models/sdp/cifar_cnn_a_adv.model  # clean acc is 6563. This is the model the authors of (Dathathri et al.) sent me but it turned out to be not the same model as reported in their paper.
data:
  dataset: CIFAR
  std: [0.2471, 0.2435, 0.2616]
  mean: [0.4914, 0.4824, 0.4467]
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 50
solver:
  batch_size: 3840
  beta-crown:
    iteration: 20
bab:
  timeout: 600
  branching:
    reduceop: max
