model:
  name: cnn_4layer
  path: models/sdp/cifar_cnn_a_mix.model  # Clean acc is 74.18%
data:
  dataset: CIFAR
  std: [0.2471, 0.2435, 0.2616]
  mean: [0.4914, 0.4824, 0.4467]
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 50
solver:
  batch_size: 3840
  beta-crown:
    iteration: 20
  mip:
    solver_threads: 8
    parallel_solvers: 1
bab:
  timeout: 300
