model:
  name: partial(crown_ibp_model_c_d_e_f, in_ch=3, in_dim=32, kernel_size=3, width=8, linear_size=256)
  path: models/crown-ibp/cifar_model_q_2px.pth  # clean acc is 6066.
data:
  dataset: CIFAR
  std: [0.2023, 0.1994, 0.2010]
  mean: [0.4914, 0.4822, 0.4465]
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 50
solver:
  batch_size: 200
  beta-crown:
    iteration: 20
bab:
  timeout: 600
