model:
  name: cifar_conv_small
  path: models/eran/cifar_conv_small_pgd.pth
data:
  dataset: CIFAR
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  max_domains: 5000000
  timeout: 300
