model:
  name: cifar_marabou_large
  path: models/marabou_cifar10/cifar_marabou_large.pth  # Clean acc is 7416.
data:
  dataset: CIFAR
  std: 1.0
  mean: 0.0
specification:
  epsilon: 0.00784313725  # 2./255.
attack:
  pgd_restarts: 50
solver:
  batch_size: 1536
  beta-crown:
    iteration: 20
bab:
  timeout: 180
  branching:
    reduceop: max
