model:
  name: mnist_cnn_4layer
  path: models/sdp/mnist_cnn_a_adv.model
data:
  dataset: MNIST
specification:
  epsilon: 0.3
attack:
  pgd_restarts: 50
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
  mip:
    solver_threads: 8
    parallel_solvers: 1
bab:
  timeout: 180
  branching:
    reduceop: max
