general:
  # root_path: ../../CIFAR100_TinyImageNet_ResNet
  # csv_name: cifar100_tinyimagenet_instances.csv
  # Following the format on https://github.com/ChristopherBrix/vnncomp2022_benchmarks
  root_path: ../../vnncomp2022_benchmarks/benchmarks/cifar100_tinyimagenet_resnet
  csv_name: instances.csv
data:
  dataset: CIFAR100
  num_outputs: 100
  start: 0  # Subject to change.
  end: 74
model:
  onnx_optimization_flags: merge_bn
attack:
  pgd_order: skip
  pgd_restarts: 10
solver:
  batch_size: 256
  # TODO: tune both alpha-crown and beta-crown parameters (learning rate, iterations, learning rate decay, AND batch size)
  beta-crown:
    iteration: 20
bab:
  initial_max_domains: 100
  # TODO: tune branching heuristic parameters.
  branching:
    reduceop: max
