# Configuration file for running the carvana_unet_2022 benchmark (unet_upsample model).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/carvana_unet_2022
  csv_name: instances.csv
  enable_incomplete_verification: False
  conv_mode: patches
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
  # Use the function customized_Carvana_loader() in custom_model_loader.py to load this model.
  onnx_loader: Customized("custom_model_loader", "customized_Carvana_loader")
specification:
  robustness_type: all-positive
data:
  num_outputs: 1
  start: 80
  end: 160
solver:
  batch_size: 64  # Number of parallel domains to compute on GPU.
  bound_prop_method: init-crown
  crown:
    batch_size: 4096
  alpha-crown:
    full_conv_alpha: False
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  initial_max_domains: 1
  decision_thresh: 1314
  branching:
    reduceop: max
    candidates: 10
attack:
  pgd_order: skip
