# Configuration file for running the cifar2020 benchmark (all properties).
general:
  root_path: ../../vnncomp2021/benchmarks/cifar2020  # Please update this path to point to the VNN-COMP 2021 repo
  csv_name: cifar2020_instances.csv
solver:
  batch_size: 200
  beta-crown:
    lr_beta: 0.01
bab:
  branching:
    reduceop: max
    candidates: 10
  initial_max_domains: 10
attack:
  pgd_order: middle
