# Configuration file for running the oval21 benchmark (all properties).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/oval21  # Please update this path to point to the VNN-COMP 2022 repo
  csv_name: instances.csv
  conv_mode: matrix
solver:
  batch_size: 2000
  beta-crown:
    lr_beta: 0.01
  start_save_best: -1
  prune_after_crown: False
bab:
  branching:
    reduceop: max
    candidates: 10
  cut:
    enabled: True
    cplex_cuts: True
    bab_cut: True
    lr_beta: 0.01
attack:
  pgd_order: middle
