# Configuration file for running the cifar100_tinyimagenet_resnet benchmark (tinyimagenet model).
general:
  root_path: ../../vnncomp2022_benchmarks/benchmarks/cifar100_tinyimagenet_resnet
  csv_name: instances.csv
data:
  num_outputs: 200
  start: 74  # Subject to change.
  end: 98
model:
  onnx_optimization_flags: merge_bn
attack:
  pgd_order: middle
  pgd_restarts: 10
solver:
  batch_size: 256
  beta-crown:
    lr_alpha: 0.05
    lr_beta: 0.1
    iteration: 5
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
bab:
  initial_max_domains: 10000
  branching:
    method: kfsb
    candidates: 7
    reduceop: max
  interm_transfer: False
