# Example for using customized model and data loader.
# Model and data loader defined in custom_model_data.py
# python abcrown.py --config exp_configs/tutorial_examples/custom_box_data_example.yaml
model:
  # Use the two_relu_toy_model() model in "custom_model_data.py".
  name: Customized("custom_model_data", "two_relu_toy_model", in_dim=2, out_dim=2)
data:
  # Use the simple_box_data() loader in "custom_model_data.py".
  dataset: Customized("custom_model_data", "simple_box_data")
  num_outputs: 2
specification:
  epsilon: 1.
attack:
  pgd_order: skip
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 30
