model:
  name: mnist_cnn_4layer
  path: models/sdp/mnist_cnn_a_adv.model
data:
  dataset: MNIST
  start: 0
  end: 100
  std: [1.]
  mean: [0.]
specification:
  epsilon: 0.3
  norm: .inf
attack:
  pgd_restarts: 50
solver:
  batch_size: 1024
  beta-crown:
    iteration: 20
bab:
  timeout: 180
