# Example of ONNX model, element-wise bounds perturbation, customized dataloader.
model:
  onnx_path: ../../vnncomp2021/benchmarks/oval21/nets/cifar_deep_kw.onnx  # Path to ONNX model.
data:
  # Use the cifar10() loader in "custom_model_data.py".
  dataset: Customized("custom_model_data", "cifar10", use_bounds=True)
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
specification:
  # Element-wise perturbation. The magnitude of each pixel is defined in the cifar10() dataloader in custom_model_data.py.
  type: box
  epsilon: 0.00784313725  # 2./255. Used by cifar10() loader to generate element-wise bounds.
attack:
  pgd_restarts: 100
solver:
  batch_size: 2048
  beta-crown:
    iteration: 20
bab:
  timeout: 300
